

/*ALTER TABLE WFEMP.INFO_PROVEEDORES
        */
DROP TABLE WFEMP.INFO_VENTAS;
DROP TABLE WFEMP.INFO_FACTURAS;
DROP TABLE WFEMP.INFO_CLIENTES;
DROP TABLE WFEMP.INFO_PRODUCTOS;
DROP TABLE WFEMP.INFO_CATEGORIAS;
DROP TABLE WFEMP.INFO_PROVEEDORES;     
        


